[tool.ruff]
line-length = 88

[tool.lint]
extend-ignore = ["E203"]

[tool.lint.per-file-ignores]
"tests/*" = ["D"]

[project]
name = "hw1-lr-visualizer"
version = "0.1.0"
description = "Interactive linear regression visualizer for HW1"
