name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install project requirements and ensure pytest is available on the runner
          python -m pip install -r requirements.txt pytest
      - name: Verify pytest installed
        run: |
          python -c "import pytest; print('pytest_ok', pytest.__version__)" | tee -a pytest-output.txt
      - name: Run tests
        run: |
          # run pytest and capture output to a file for artifact upload
          python -m pytest -q | tee pytest-output.txt
      - name: Upload pytest output
        uses: actions/upload-artifact@v4
        with:
          name: pytest-output
          path: pytest-output.txt
